### ISSUE TITLE
In-Chat Statistics / Change to /stats command

### ISSUE THREAD

**Issue by crtrue** [GreyWuffGames/Werewolf#196]
I run the @wolfcardbot Werewolf statistics bot, which essentially just scrapes the website and posts a user's current statistics. It has proven to be surprisingly popular in a number of chats, to the point where I'm wondering why it isn't a feature in the main bot. Scraping the site as a third-party is fine but I feel as if this is one of those no-brainer suggestions.

Rather than using my separate bot, just alter the /stats command to duplicate @wolfcardbot's functionality. Perhaps add a link to the bottom of the stat post so people can view their awards on the website. i.e.:

> **Me**:
> **/stats@werewolfbot**
>
> **wolfcardbot**:
> GRAVYLORD
> Typically a Mason
> Wins: 1000000
> Losses: 0
> Survived: 2
> Total Games: A lot
> Blah blah
> **Click here to view your achievements** (link to website)

**Comment by parabola949** [comment]
What if we made werewolf inline, and you could select stats for self,
group, global.  Then we could probably also add some other inline commands
as well.

I left the functionality with your bot because you did a good job and I
didn't want to steal that from you.  If you are OK with me adding it, then
I gladly will :)

**Comment by crtrue** [comment]
I don't want to pay money for hosting. Take it baby.

**Comment by parabola949** [comment]
@crtrue Done sweetie
